spring.application.name=student_management

# ==============================
# PostgreSQL Configuration
# ==============================

spring.datasource.url=jdbc:postgresql://localhost:5432/contact_book
spring.datasource.username=postgres
spring.datasource.password=password

# ==============================
# JPA / Hibernate Configuration
# ==============================

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Server Configuration
# ==============================

server.port=8082